# Generated by Django 2.2.6 on 2019-12-24 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Name of the Post', max_length=120, unique=True)),
                ('description', models.CharField(blank=True, help_text='Brief description', max_length=1300, null=True)),
                ('category', models.CharField(help_text='Category, the Post belongs to', max_length=120, null=True)),
                ('sub_category', models.CharField(blank=True, help_text='If the Post is from a sub category', max_length=120, null=True)),
                ('thumbnail', models.CharField(help_text='Thumbnail Slug of the image', max_length=1000, null=True)),
                ('full_res_image', models.CharField(help_text='Slug of the image', max_length=1000, null=True)),
                ('universal_count', models.IntegerField(help_text='Count of post in Overall posts')),
                ('category_count', models.IntegerField(help_text='Count of Post in a category')),
                ('sub_post_count', models.IntegerField(blank=True, help_text='Count of post in sub category (if any)', null=True)),
                ('is_printable', models.BooleanField(default=False, help_text='Can it be printed on t-Shirt')),
                ('tags', models.CharField(blank=True, help_text='Significant words used in Post', max_length=1000, null=True)),
                ('views', models.IntegerField()),
                ('downloads', models.IntegerField()),
                ('shares', models.IntegerField(default=0)),
                ('custom_ordering', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
