# Generated by Django 2.2.5 on 2019-09-07 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=120, null=True)),
                ('storage_link', models.CharField(max_length=1000, null=True)),
                ('universal_count', models.IntegerField(max_length=20)),
                ('category_count', models.IntegerField(max_length=20)),
                ('sub_post_count', models.IntegerField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
