# Generated by Django 2.2.6 on 2019-10-08 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=1300, null=True)),
                ('category', models.CharField(max_length=120, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=120, null=True)),
                ('storage_link', models.CharField(max_length=1000, null=True)),
                ('universal_count', models.IntegerField()),
                ('category_count', models.IntegerField()),
                ('sub_post_count', models.IntegerField(blank=True, null=True)),
                ('is_printAvailible', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=1000, null=True)),
                ('views', models.IntegerField()),
                ('downloads', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
