# Generated by Django 2.2.6 on 2019-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_ordering',
            field=models.IntegerField(default=0),
        ),
    ]
