# Generated by Django 2.2.6 on 2020-01-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_trial_content',
            field=models.CharField(default='SubscribedContent', help_text='If Post belongs in onTrial Content, Just Set NotSubscribedContent, otherwise SubscribedContent', max_length=50, null=True),
        ),
    ]
