# Generated by Django 2.2.6 on 2019-10-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=1300, null=True)),
                ('sub_categories', models.CharField(blank=True, max_length=120, null=True)),
                ('pic_top', models.CharField(max_length=300)),
                ('pic_left', models.CharField(max_length=300)),
                ('pic_right', models.CharField(max_length=300)),
                ('count_range_from', models.IntegerField()),
                ('count_range_to', models.IntegerField()),
                ('tags', models.CharField(max_length=500)),
                ('total_posts_count', models.IntegerField()),
            ],
        ),
    ]
