# Generated by Django 2.2.6 on 2019-10-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(help_text='Unique Id', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Name of the category', max_length=120, unique=True)),
                ('description', models.CharField(blank=True, help_text='Brief Description', max_length=1300, null=True)),
                ('sub_categories', models.CharField(blank=True, help_text='If any', max_length=120, null=True)),
                ('pic_top', models.CharField(max_length=300)),
                ('pic_left', models.CharField(max_length=300)),
                ('pic_right', models.CharField(max_length=300)),
                ('count_range_from', models.IntegerField(help_text='Universal Count where this category starts')),
                ('count_range_to', models.IntegerField(help_text='Universal Count where this category ends')),
                ('tags', models.CharField(help_text='Tags for modified searching', max_length=500)),
                ('total_posts_count', models.IntegerField()),
            ],
        ),
    ]
