# Generated by Django 2.2.6 on 2019-12-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrashCourse',
            fields=[
                ('id', models.CharField(help_text='Unique Id', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Name of the Crash Course', max_length=120, unique=True)),
                ('description', models.CharField(blank=True, help_text='Brief Description', max_length=1300, null=True)),
                ('pic_top', models.CharField(max_length=300)),
                ('pic_left', models.CharField(max_length=300)),
                ('pic_right', models.CharField(max_length=300)),
                ('count_range_from', models.IntegerField(help_text='Universal Count in Articles where this CrashCourse starts')),
                ('count_range_to', models.IntegerField(help_text='Universal Count in Articles where this CrashCourse ends')),
                ('first_article_url', models.CharField(help_text='Url of first article in Crash Course', max_length=250)),
                ('last_article_url', models.CharField(help_text='Url of first article in Crash Course', max_length=250)),
                ('tags', models.CharField(help_text='Tags for modified searching', max_length=500)),
                ('total_articles_count', models.IntegerField()),
            ],
        ),
    ]
