# Generated by Django 2.2.6 on 2019-12-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashcourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashcourse',
            name='source',
            field=models.CharField(default='blank', help_text='Source of the Crash Course', max_length=120),
        ),
    ]
