# Generated by Django 2.2.6 on 2019-12-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashcourses', '0002_auto_20191224_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashcourse',
            name='author_image',
            field=models.CharField(default='blank', help_text='Image of the author', max_length=200),
        ),
        migrations.AddField(
            model_name='crashcourse',
            name='author_info',
            field=models.CharField(default='blank', help_text='Few lines aobut the author', max_length=200),
        ),
        migrations.AddField(
            model_name='crashcourse',
            name='author_name',
            field=models.CharField(default='blank', help_text='Author Of The Source', max_length=100),
        ),
    ]
