# Generated by Django 2.2.6 on 2020-01-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashcourses', '0003_auto_20191224_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashcourse',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Is the course finished? or on going'),
        ),
    ]
