# Generated by Django 2.2.6 on 2020-01-25 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserJoke',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('username', models.CharField(help_text='Username of the user', max_length=120)),
                ('email', models.CharField(help_text='Email Of The User', max_length=100)),
                ('build_up', models.CharField(help_text='Build up or first line of the joke', max_length=1300, null=True)),
                ('delivery', models.CharField(blank=True, help_text='2nd Part of joke : if joke is only one liner then leave this one empty', max_length=300, null=True)),
                ('type', models.CharField(blank=True, help_text='Type of joke : User will choose from pre-defined choices', max_length=120, null=True)),
                ('slug', models.CharField(blank=True, help_text='Gif/Thumb/other Url - If Any', max_length=120, null=True)),
                ('thumbs_ups', models.IntegerField(default=0)),
                ('thumbs_downs', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
