# Generated by Django 2.2.6 on 2020-01-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.CharField(help_text='Accepted Input : FeedsAnnouncement, CategoryAnnouncement, CrashCourseAnnouncement', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('heading', models.CharField(help_text='Heading Of The Announcement', max_length=120, unique=True)),
                ('message', models.CharField(blank=True, help_text='Message Of The Announcement', max_length=1300, null=True)),
            ],
        ),
    ]
