# Generated by Django 2.2.6 on 2020-01-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='heading',
            field=models.CharField(help_text='Heading Of The Announcement', max_length=120),
        ),
    ]
