# Generated by Django 2.2.6 on 2019-12-24 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('user_email', models.EmailField(help_text='Email of the Subscriber', max_length=100)),
                ('order_id', models.CharField(help_text='Order Id From the Purchase', max_length=200)),
                ('purchase_token', models.CharField(help_text='Token From The Purchase', max_length=200)),
                ('sku_product', models.CharField(help_text='Product Which was subscribed to', max_length=100)),
                ('package_name', models.CharField(help_text='App For Which The Purchase Was Made', max_length=100)),
                ('developer_payload', models.CharField(blank=True, help_text='Developer payload From The Purchase', max_length=500, null=True)),
                ('original_json', models.CharField(blank=True, help_text='Original Json from purchase', max_length=1000, null=True)),
                ('purchase_status', models.CharField(choices=[('UNSPECIFIED_STATE', 0), ('PENDING', 2), ('PURCHASED', 1)], default='UNSPECIFIED_STATE', help_text=' 0:Unspecified  1:Purchased  2:Pending ', max_length=40)),
                ('purchase_time', models.CharField(help_text='Time Of Purchase', max_length=200, null=True)),
                ('is_acknowledged', models.BooleanField(default=False, help_text='Is the Purchase Acknowledged?')),
                ('is_auto_renewing', models.BooleanField(default=False, help_text='Is the Subscription AutoRenewing?')),
                ('purchase_signature', models.CharField(blank=True, help_text='Purchase Signature', max_length=1000)),
                ('is_active', models.BooleanField(default=False, help_text='Is the Subscription Active or canceled?')),
            ],
        ),
    ]
