# Generated by Django 2.2.6 on 2019-10-17 20:32

import creditcards.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('product_id', models.CharField(help_text='Product which user ordered', max_length=50)),
                ('user_id', models.CharField(help_text='Id of the user who placed the order', max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('phone_number_with_code', models.CharField(max_length=20)),
                ('full_address', models.CharField(max_length=128, verbose_name='address')),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(default='43701', max_length=5, verbose_name='zip code')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('cc_expiry', creditcards.models.CardExpiryField(null=True, verbose_name='expiration date')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
                ('order_status', models.CharField(choices=[('pending', 'PENDING'), ('shipped', 'SHIPPED'), ('completed', 'COMPLETED')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
