# Generated by Django 2.2.6 on 2019-10-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplashcategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsplashcategory',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of category', max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='unsplashcategory',
            name='related_tags',
            field=models.CharField(help_text='Related searches that appear after search', max_length=500),
        ),
        migrations.AlterField(
            model_name='unsplashcategory',
            name='title',
            field=models.CharField(help_text='Name of the category', max_length=120, unique=True),
        ),
    ]
