# Generated by Django 2.2.6 on 2019-12-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name of the product', max_length=100)),
                ('description', models.CharField(help_text='Brief description of Product/Design printed on it', max_length=1000)),
                ('quantity_in_stock', models.IntegerField(help_text='Available quantity')),
                ('sales', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shipment_charges', models.IntegerField()),
                ('photos', models.CharField(max_length=2000)),
            ],
        ),
    ]
